---
# file: roles/geoserver/tasks/main.yml

- name: ensure unzip is installed
  apt: pkg=unzip state=installed

- name: check if geoserver exists
  shell: "[ -e /var/lib/tomcat7/webapps/geoserver.war ] && echo 'Found' || echo ''"
  register: geoserver_installed

- name: download and deploy geoserver
  include: download_install.yml
  when: (not geoserver_installed.stdout)

- name: enable apache proxy modules
  command: a2enmod proxy proxy_ajp
  sudo: yes
  notify: restart apache

- name: copy proxy configuration
  copy: src=proxy.conf dest=/etc/apache2/conf-enabled/proxy.conf
  notify: restart apache


