---
# file: roles/geoserver/tasks/main.yml

- name: check if geoserver exists
  shell: "[ -e /var/lib/tomcat7/webapps/geoserver.war ] && echo 'Found' || echo ''"
  register: geoserver_installed

- name: download and deploy geoserver
  include: download_install.yml
  when: (not geoserver_installed.stdout)

- name: enable apache proxy modules
  command: a2enmod proxy proxy_ajp
  sudo: yes
  notify: restart apache

- name: copy geoserver configuration
  copy: src=geoserver.conf dest=/etc/apache2/conf-enabled/geoserver.conf
  notify: restart apache


