---
# file: roles/web/tasks/main.yml

- name: ensure apache is installed
  apt: pkg=apache2 state=installed

- name: ensure apache2 is running
  service: name=apache2 state=started

- name: add oracle-java ppa
  apt_repository: repo=ppa:webupd8team/java state=present

- name: automatically accept oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install oracle-java7
  apt: pkg=oracle-java7-installer state=latest update-cache=yes force=yes

- name: ensure tomcat7 is installed
  action: apt pkg={{item}} state=installed
  with_items:
    - tomcat7
    - tomcat7-admin

- name: ensure tomcat7 is running
  service: name=tomcat7 state=started

- name: copy tomcat-users.xml
  copy: src=tomcat-users.xml dest=/etc/tomcat7/tomcat-users.xml
  notify: restart tomcat

- name: copy server.xml
  copy: src=server.xml dest=/etc/tomcat7/server.xml
  notify: restart tomcat
