---
# file: roles/web/tasks/main.yml

- name: ensure apache is installed
  apt: pkg=apache2 state=latest
  sudo: yes  

- name: ensure apache2 is running
  service: name=apache2 state=started
  sudo: yes  

# TODO install oracle java

- name: ensure tomcat7 is installed
  action: apt pkg={{item}} state=installed
  with_items:
    - tomcat7
    - tomcat7-admin
  sudo: yes

- name: ensure tomcat7 is running
  service: name=tomcat7 state=started
  sudo: yes   

- name: copy tomcat-users.xml
  copy: src=tomcat-users.xml dest=/etc/tomcat7/tomcat-users.xml
  sudo: yes
  notify: restart tomcat

- name: copy server.xml
  copy: src=server.xml dest=/etc/tomcat7/server.xml
  sudo: yes
  notify: restart tomcat